### ISSUE TITLE
TODO list for v0.32

### ISSUE THREAD

**Issue by fwsGonzo** [libriscv/godot-sandbox#229]
- [ ] I really want to make emitting binary translation C99 code easier. I want to place a button somewhere, so that if I click on a Sandbox node I can just click a button to write out the binary translation. Currently I have to write a tiny GDScript that writes the translation to a file.
- [ ] I also want to make a button to emit the run-time generated API manually. Where?
- [x] Make the public API more dynamic, allow it from main()
- [x] Update the Rust API to be able to use the (dynamic) public API
- [x] Easily download a named program from this repo, eg. `Sandbox.download("hello_world")`

**Comment by fire** [comment]
> I also want to make a button to emit the run-time generated API manually. Where?

Probably to `.godot` folder somewhere or `user://`

**Comment by fwsGonzo** [comment]
I just made v0.32 without buttons/context menuing to generate binary translation or run-time API. Next release.
